---
name: Tests

on:
  push:
    branches:
      - master
      - github-workflows
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        django: [2.2.17, 3.0.11, 3.1.3, 3.2.0, 4.0]
        include:
          - python-version: "3.10"
            django: 3.2.0

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install latest pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip wheel setuptools
      - name: Install dependencies
        run: |
          PACKAGES=('pytest' 'pytest-django' 'djangorestframework' 'freezegun')
          if [[ "${{ matrix.django }}" == 'main' ]]; then
              PACKAGES+=('https://github.com/django/django/archive/main.tar.gz');
          else
              PACKAGES+=("Django~=${{ matrix.django }}");
          fi;

          python -m pip install --upgrade --upgrade-strategy=only-if-needed ${PACKAGES[*]};
      - name: Ensure no version conflicts exist
        run: pip check

      - name: Code tests (with SQLite)
        run: |
          PYTHONPATH=. py.test
